language: python

python:
  - "2.7"
#   - "3.4"
#   - "3.5"
  - "3.6"
#  - "3.7"

env:
  - DUNDEE_TEMPDIR=images_resample DUNDEE_RESOLUTION=high DUNDEE_NPROCS=2 DUNDEE_PROJECTION=pyresample

before_install:
  - sudo apt-get install libproj-dev proj-bin proj-data
  - wget http://us.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj9_4.9.2-2_amd64.deb 
  - sudo dpkg -i libproj9_4.9.2-2_amd64.deb 
  - wget http://us.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj-dev_4.9.2-2_amd64.deb
  - sudo dpkg -i libproj-dev_4.9.2-2_amd64.deb
  - sudo apt-get install libgeos-dev
#  - sudo ln -s /usr/lib/libgeos-3.*.so /usr/lib/libgeos.so
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - sudo apt-get install imagemagick # need this for "file" output

script: 
  - mkdir -p $HOME/.CreateCloudMap
  - sh ./tests/create_cfg.sh
  - python setup.py sdist --format=gztar
  - ls dist/CreateCloudMap-*.tar.gz
  - export PKG=`ls dist/CreateCloudMap-*.tar.gz`
  - pip install $PKG
  - create_map -h
  - create_map --version
  - create_map -m 23
  - identify xplanet/images/clouds_2048.jpg
  - rm xplanet/images/clouds_2048.jpg
  - pip install cython
  - pip install pyproj==2.0.2
  - pip install ${PKG}[debug_cartopy]
  - pip uninstall matplotlib -y
  - pip install matplotlib 
  - pip install git+https://github.com/matplotlib/basemap
  - pip install ${PKG}[debug_pyresample]
  - create_map -d -m 23
  - identify xplanet/images/clouds_2048.jpg
  - rm xplanet/images/clouds_2048.jpg
